# Builds (and can resume/extend) a fixed pool of TrainingExamples generated by
# pure, network-free MCTS at config['mcts']['pretrain_mcts_depth'], saved to
# PretrainExamples/pool.pkl. PretrainManager.py trains against this pool with no
# self-play and no gating. generate_pool() is idempotent (a no-op once the pool
# already meets target), which is what lets Pretrain.py call it unconditionally
# every run as the first step of a single fire-and-forget entry point - this
# file's own __main__ block just calls it directly, so it still works standalone
# too (e.g. to top up the pool later for a bigger run).
import os
import time
import pickle
import multiprocessing as mp

from simulate_raw_mcts_games import simulate_raw_mcts_games
from Config import config

POOL_PATH = 'PretrainExamples/pool.pkl'


def load_pool(path=POOL_PATH):
    if not os.path.exists(path):
        return []
    with open(path, 'rb') as file:
        return pickle.load(file)


def save_pool(pool, path=POOL_PATH):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'wb') as file:
        pickle.dump(pool, file)


def run_batch(num_processes, mp_manager):
    # Same shape as TrainingManager.run_self_play: one apply_async per process,
    # each running num_of_self_play_games_per_process games, results collected via
    # a shared progress queue for one consolidated, ETA'd print stream.
    games_per_process = config['self_play']['num_of_self_play_games_per_process']
    total_games = num_processes * games_per_process

    progress_queue = mp_manager.Queue()

    batch_examples = []
    pool = mp.Pool(num_processes)
    for _ in range(num_processes):
        pool.apply_async(simulate_raw_mcts_games, args=(progress_queue,), callback=batch_examples.extend)
    pool.close()

    games_done = 0
    start_time = time.time()
    while games_done < total_games:
        pid, game_idx, worker_num_games, plies, duration = progress_queue.get()
        games_done += 1
        elapsed = time.time() - start_time
        eta = (elapsed / games_done) * (total_games - games_done)
        print(f'  [{games_done}/{total_games}] worker {pid}: game {game_idx}/{worker_num_games} '
              f'({plies} plies, {duration:.1f}s) - elapsed {elapsed:.0f}s, ETA ~{eta:.0f}s')

    pool.join()
    return batch_examples


def generate_pool(path=POOL_PATH):
    target = config['training']['max_training_examples']
    depth = config['mcts']['pretrain_mcts_depth']
    num_processes = config['self_play']['num_of_processes']

    training_pool = load_pool(path)
    if training_pool:
        print(f'Resuming pool of {len(training_pool)}/{target} examples at {path} (raw MCTS depth {depth})')
    else:
        print(f'Starting a new pool - target {target} examples at raw MCTS depth {depth}')

    if len(training_pool) >= target:
        print('Pool already meets target - nothing to do.')
        return training_pool

    mp_manager = mp.Manager()
    batch_num = 0
    run_start_time = time.time()

    while len(training_pool) < target:
        batch_num += 1
        print(f'\n--- Batch {batch_num}: {len(training_pool)}/{target} examples so far ---')
        batch_start_time = time.time()

        training_pool.extend(run_batch(num_processes, mp_manager))
        save_pool(training_pool, path)

        print(f'Batch {batch_num} done in {time.time() - batch_start_time:.1f}s '
              f'- pool now {len(training_pool)}/{target}')

    # Trim to the exact target so the saved pool size always matches
    # max_training_examples, even though the last batch likely overshot it.
    training_pool = training_pool[:target]
    save_pool(training_pool, path)

    print(f'\nPool generation done in {time.time() - run_start_time:.1f}s. '
          f'Pool has {len(training_pool)} examples at {path}.')
    return training_pool


if __name__ == '__main__':
    generate_pool()
